version: '3'

services:

  prisma:
    container_name: prisma
    image: prismagraphql/prisma:1.34
    restart: always
    depends_on:
      - postgres
    networks:
      - timeline-service
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: postgres
            user: prisma
            password: prisma
            rawAccess: false
            port: 5432
            migrations: true

  postgres:
    container_name: postgres
    image: postgres:alpine
    restart: always
    # Uncomment the next two lines to connect to your your database from outside the Docker environment, e.g. using a database GUI like Postico
    networks:
      - timeline-service
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - timeline-service
    ports:
      - "6379:6379"

  timeline:
    container_name: timeline-service
    depends_on:
      - redis
      - postgres
      - prisma
    build: .
    environment:
      PRISMA_ENDPOINT: http://prisma:4466
    image: timeline-service
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - timeline-service
    ports:
      - "4000:4000"

volumes:
  postgres:

networks:
  timeline-service:
